# This is a basic workflow to help you get started with Actions

name: CI
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  info: 
    runs-on: ubuntu-latest
    steps:
    - name: Print Info
      run: echo '{{github}}'
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: manojsingh-manoj/SpringBEx
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - uses: actions/upload-artifact@v4
        with:
         name: my-artifact
         path: target/*.jar
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          java -version
  deploy:
    needs: build
    runs-on: self-hosted
    steps:
     - name: print hello world
       run: echo "Hello, this is deploy job"
   
