# This is a basic workflow to help you get started with Actions

name: CI Demo
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  info: 
    runs-on: ubuntu-latest
    steps:
    - name: Printing the Context
      run: echo "${{ toJSON(github) }}"
  build:
    needs: info
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: manojsingh-manoj/SpringBEx
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build the artifact
        run: mvn -B package --file pom.xml
      - name: Rename JAR with Build Number
        run: |
            build_number=$(echo "${GITHUB_RUN_NUMBER}" | tr -d '\n')
            jar_file=$(ls target/*.jar | head -n 1)
            jar_name=$(basename "${jar_file}" .jar)
            artifact_name="myapplicationjarname-build-${build_number}.jar"
      - uses: actions/upload-artifact@v4
        with:
         name: artifact-name
         path: target/*.jar
      - name: Run a multi-line script
        run:  java -version
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
     - name: print hello world
       run: echo "Hello, this is deploy job"
   
