# This is a basic workflow to help you get started with Actions

name: CI Demo
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  info: 
    runs-on: ubuntu-latest
    steps:
    - name: Printing the Context
      run: echo "${{ toJSON(github) }}"
  build:
    needs: info
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: manojsingh-manoj/SpringBEx
      - name: Build the artifact
        run: mvn -B package --file pom.xml
      - name: Rename JAR with Build Number
        run: |
          build_number=$(echo "${GITHUB_RUN_NUMBER}" | tr -d '\n')
          jar_name=$(ls target/*.jar | head -n 1)
          mv "${jar_name}" "${jar_name%.*}-bn-${build_number}.jar"
          artifact_name="${jar_name}-bn-${build_number}"
          
          echo "Uploading artifact: ${artifact_name}"
          echo "::set-output name=artifact_name::${artifact_name}"
        id: set_artifact_name
      - uses: actions/upload-artifact@v4
        with:
         name: ${{ steps.set_artifact_name.outputs.artifact_name }}
         path: target/*.jar
      - name: Run a multi-line script
        run:  java -version
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
     - name: print hello world
       run: echo "Hello, this is deploy job"
   
